import {
  User,
  Product,
  Lead,
  Customer,
  SiteSurvey,
  Quotation,
  Order,
  Project,
  Invoice,
  Payment,
  FollowUp,
  AuditLog,
  InventoryTransaction,
  ProjectHardwareAllocation,
  InstallationJob,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Vikramaditya Sharma',
    email: 'vikram@nitishsolar.com',
    role: 'SUPER_ADMIN',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Rajesh Mehta',
    email: 'rajesh.m@nitishsolar.com',
    role: 'ADMIN',
    phone: '+91 98112 33445',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Ananya Verma',
    email: 'ananya.v@nitishsolar.com',
    role: 'SALES_MANAGER',
    phone: '+91 97123 45678',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Siddharth Patel',
    email: 'siddharth.p@nitishsolar.com',
    role: 'SALES_EXECUTIVE',
    phone: '+91 99887 76655',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-01-20T08:30:00Z',
  },
  {
    id: 'user-5',
    name: 'Priya Iyer',
    email: 'priya.i@nitishsolar.com',
    role: 'PROJECT_MANAGER',
    phone: '+91 98220 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-02-01T09:15:00Z',
  },
  {
    id: 'user-6',
    name: 'Amitabh Joshi',
    email: 'amitabh.j@nitishsolar.com',
    role: 'FINANCE',
    phone: '+91 99334 55667',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-02-05T14:00:00Z',
  },
  {
    id: 'user-7',
    name: 'Rohan Gupta',
    email: 'rohan.g@nitishsolar.com',
    role: 'VIEWER',
    phone: '+91 96543 21098',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
    active: true,
    createdAt: '2025-02-10T10:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'nitish solar Apex 540W N-Type TOPCon Panel',
    sku: 'PAN-TOP-540',
    type: 'SOLAR_PANEL',
    brand: 'nitish solar Tech',
    specifications: {
      wattage: 540,
      efficiency: '22.8%',
      cellType: 'N-Type TOPCon',
      dimensions: '2278 x 1134 x 35 mm',
      weight: '27.5 kg',
    },
    unitPrice: 14500,
    pricePerWatt: 26.8,
    stockQuantity: 1200,
    warrantyYears: 30,
    imageUrl: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'prod-2',
    name: 'nitish solar Bifacial Dual Glass 580W Panel',
    sku: 'PAN-BIF-580',
    type: 'SOLAR_PANEL',
    brand: 'nitish solar Tech',
    specifications: {
      wattage: 580,
      efficiency: '23.2%',
      cellType: 'Bifacial Glass-Glass',
      bifacialGain: 'Up to 25%',
    },
    unitPrice: 16800,
    pricePerWatt: 28.9,
    stockQuantity: 850,
    warrantyYears: 30,
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'prod-3',
    name: 'Aether Grid-Tie 10kW Three-Phase Inverter',
    sku: 'INV-3PH-10K',
    type: 'INVERTER',
    brand: 'Aether Power',
    specifications: {
      capacityKw: 10,
      mpptCount: 2,
      maxEfficiency: '98.6%',
      protection: 'IP65 Water & Dust Proof',
    },
    unitPrice: 62000,
    stockQuantity: 140,
    warrantyYears: 10,
    imageUrl: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'prod-4',
    name: 'Aether Commercial 50kW String Inverter',
    sku: 'INV-COM-50K',
    type: 'INVERTER',
    brand: 'Aether Power',
    specifications: {
      capacityKw: 50,
      mpptCount: 5,
      maxEfficiency: '98.8%',
      gridType: '415V Three Phase',
    },
    unitPrice: 215000,
    stockQuantity: 45,
    warrantyYears: 10,
    imageUrl: 'https://images.unsplash.com/photo-1558441719-443b38605AD4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'prod-5',
    name: 'nitish solar Titan 15kWh LiFePO4 Battery System',
    sku: 'BAT-LFP-15K',
    type: 'BATTERY_STORAGE',
    brand: 'nitish solar Storage',
    specifications: {
      capacityKwh: 15,
      chemistry: 'LiFePO4',
      cycleLife: '6000+ Cycles',
      dodPct: 90,
    },
    unitPrice: 285000,
    stockQuantity: 60,
    warrantyYears: 10,
    imageUrl: 'https://images.unsplash.com/photo-1548611716-3001815195e3?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'prod-6',
    name: 'Hot Dip Galvanized Solar Mounting Structure',
    sku: 'STR-HDG-KW',
    type: 'MOUNTING_STRUCTURE',
    brand: 'nitish solar Structures',
    specifications: {
      material: 'HDG Steel 80 Micron',
      windRating: '170 km/h',
      tiltRange: '15 - 25 degrees',
    },
    unitPrice: 4200,
    stockQuantity: 5000,
    warrantyYears: 25,
  },
  {
    id: 'prod-7',
    name: 'Complete Balance of System (BOS) Kit 10kW',
    sku: 'BOS-KIT-10K',
    type: 'BOS_CABLE_SWITCHGEAR',
    brand: 'nitish solar Electricals',
    specifications: {
      dcCable: '4sqmm Twin Core UV Resistant',
      acCable: '10sqmm 4 Core Armor',
      acdbDcdb: 'IP65 Enclosure with SPD & MCBs',
      earthing: 'Chemical Earthing Kit x 3',
    },
    unitPrice: 38000,
    stockQuantity: 180,
    warrantyYears: 5,
  },
  {
    id: 'prod-8',
    name: 'Smart IoT Solar Monitoring Gateway & Weather Sensor',
    sku: 'MON-IOT-GW',
    type: 'MONITORING_SYSTEM',
    brand: 'Aether IoT',
    specifications: {
      connectivity: '4G LTE + Wi-Fi + RS485',
      sensors: 'Irradiance + Ambient Temp + Cell Temp',
    },
    unitPrice: 18500,
    stockQuantity: 95,
    warrantyYears: 5,
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    leadNumber: 'LD-2025-001',
    fullName: 'Sunil Gavaskar',
    email: 'sunil.g@greenwaytextiles.com',
    phone: '+91 98200 45123',
    companyName: 'Greenway Textiles Pvt Ltd',
    customerType: 'INDUSTRIAL',
    address: 'Plot 45, GIDC Industrial Estate',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pinCode: '382445',
    monthlyBillAmount: 450000,
    proposedCapacityKw: 250,
    roofType: 'Industrial Metal Roof Shed',
    roofAreaSqFt: 25000,
    status: 'SURVEY_SCHEDULED',
    priority: 'URGENT',
    source: 'Website Quote Calculator',
    notes: 'Requires 250 kWp grid tied system for factory power cost reduction. Sanctioned load is 400 kVA.',
    assignedToId: 'user-4',
    assignedToName: 'Siddharth Patel',
    createdAt: '2025-02-10T10:30:00Z',
    updatedAt: '2025-02-14T09:15:00Z',
  },
  {
    id: 'lead-2',
    leadNumber: 'LD-2025-002',
    fullName: 'Dr. Ramesh Chandra',
    email: 'dr.ramesh@cityhospital.org',
    phone: '+91 94140 88990',
    companyName: 'City Lifeline Hospital',
    customerType: 'COMMERCIAL',
    address: '12 Ring Road, Civil Lines',
    city: 'Jaipur',
    state: 'Rajasthan',
    pinCode: '302006',
    monthlyBillAmount: 180000,
    proposedCapacityKw: 100,
    roofType: 'Flat RCC Roof',
    roofAreaSqFt: 11000,
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    source: 'Trade Expo',
    notes: 'Hospital requires continuous power backup with hybrid battery storage option.',
    assignedToId: 'user-4',
    assignedToName: 'Siddharth Patel',
    createdAt: '2025-02-08T11:00:00Z',
    updatedAt: '2025-02-12T14:30:00Z',
  },
  {
    id: 'lead-3',
    leadNumber: 'LD-2025-003',
    fullName: 'Kavita Deshmukh',
    email: 'kavita.d@gmail.com',
    phone: '+91 98901 23456',
    customerType: 'RESIDENTIAL',
    address: '74 Sunrise Villa, Koregaon Park',
    city: 'Pune',
    state: 'Maharashtra',
    pinCode: '411001',
    monthlyBillAmount: 14000,
    proposedCapacityKw: 8,
    roofType: 'Terrace Concrete',
    roofAreaSqFt: 900,
    status: 'WON',
    priority: 'MEDIUM',
    source: 'Customer Referral',
    notes: 'Residential rooftop solar under PM Surya Ghar Muft Bijli Yojana with subsidy.',
    assignedToId: 'user-4',
    assignedToName: 'Siddharth Patel',
    createdAt: '2025-01-28T09:00:00Z',
    updatedAt: '2025-02-05T16:00:00Z',
  },
  {
    id: 'lead-4',
    leadNumber: 'LD-2025-004',
    fullName: 'Harpreet Singh',
    email: 'harpreet@singhlogistics.co.in',
    phone: '+91 98140 77665',
    companyName: 'Singh Logistics Park',
    customerType: 'COMMERCIAL',
    address: 'GT Road Warehouse Complex',
    city: 'Ludhiana',
    state: 'Punjab',
    pinCode: '141003',
    monthlyBillAmount: 320000,
    proposedCapacityKw: 180,
    roofType: 'Tin Shed Slope',
    roofAreaSqFt: 18000,
    status: 'NEGOTIATING',
    priority: 'HIGH',
    source: 'Website Lead Form',
    notes: 'Negotiating final milestone payment schedule and performance warranty clause.',
    assignedToId: 'user-3',
    assignedToName: 'Ananya Verma',
    createdAt: '2025-02-01T14:20:00Z',
    updatedAt: '2025-02-13T11:45:00Z',
  },
  {
    id: 'lead-5',
    leadNumber: 'LD-2025-005',
    fullName: 'Vijay Nair',
    email: 'vijay.nair@nairflats.com',
    phone: '+91 97450 11223',
    companyName: 'Emerald Heights Apartment OA',
    customerType: 'RESIDENTIAL',
    address: 'Marine Drive Block B',
    city: 'Kochi',
    state: 'Kerala',
    pinCode: '682031',
    monthlyBillAmount: 85000,
    proposedCapacityKw: 45,
    roofType: 'High-rise Flat RCC',
    roofAreaSqFt: 4500,
    status: 'NEW',
    priority: 'MEDIUM',
    source: 'Digital Ad Campaign',
    notes: 'Apartment society common area lighting and elevator solar power conversion.',
    assignedToId: 'user-4',
    assignedToName: 'Siddharth Patel',
    createdAt: '2025-02-14T08:00:00Z',
    updatedAt: '2025-02-14T08:00:00Z',
  },
  {
    id: 'lead-6',
    leadNumber: 'LD-2025-006',
    fullName: 'Manish Agarwal',
    email: 'm.agarwal@agarwalcoldstorage.com',
    phone: '+91 98300 99887',
    companyName: 'Agarwal Cold Storage & Logistics',
    customerType: 'INDUSTRIAL',
    address: 'NH-2 Highway Km 18',
    city: 'Mathura',
    state: 'Uttar Pradesh',
    pinCode: '281001',
    monthlyBillAmount: 750000,
    proposedCapacityKw: 500,
    roofType: 'Ground Mount & Metal Roof',
    roofAreaSqFt: 45000,
    status: 'CONTACTED',
    priority: 'URGENT',
    source: 'Direct Telecall',
    notes: '500 kW mega captive solar plant requirement. Cold storage operates 24/7.',
    assignedToId: 'user-3',
    assignedToName: 'Ananya Verma',
    createdAt: '2025-02-11T16:40:00Z',
    updatedAt: '2025-02-13T10:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    customerNumber: 'CUST-2025-001',
    leadId: 'lead-3',
    fullName: 'Kavita Deshmukh',
    email: 'kavita.d@gmail.com',
    phone: '+91 98901 23456',
    customerType: 'RESIDENTIAL',
    address: '74 Sunrise Villa, Koregaon Park',
    city: 'Pune',
    state: 'Maharashtra',
    pinCode: '411001',
    discomName: 'MSEDCL Pune Circle',
    consumerNumber: '01294829381',
    sanctionedLoadKw: 10,
    createdAt: '2025-02-05T16:00:00Z',
  },
  {
    id: 'cust-2',
    customerNumber: 'CUST-2025-002',
    fullName: 'Apex Auto Components Ltd',
    email: 'purchase@apexauto.in',
    phone: '+91 98230 11998',
    companyName: 'Apex Auto Components Ltd',
    customerType: 'INDUSTRIAL',
    address: 'Plot A-12, MIDC Chakan',
    city: 'Pune',
    state: 'Maharashtra',
    pinCode: '410501',
    discomName: 'MSEDCL Industrial',
    consumerNumber: '09812739182',
    sanctionedLoadKw: 350,
    createdAt: '2025-01-15T11:20:00Z',
  },
  {
    id: 'cust-3',
    customerNumber: 'CUST-2025-003',
    fullName: 'St. Xavier Educational Trust',
    email: 'admin@stxavierschool.edu',
    phone: '+91 98450 66778',
    companyName: 'St. Xavier School Campus',
    customerType: 'COMMERCIAL',
    address: 'Outer Ring Road, Marathahalli',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560037',
    discomName: 'BESCOM East',
    consumerNumber: '4452198734',
    sanctionedLoadKw: 120,
    createdAt: '2025-01-20T14:30:00Z',
  },
];

export const INITIAL_SURVEYS: SiteSurvey[] = [
  {
    id: 'surv-1',
    surveyNumber: 'SURV-2025-001',
    leadId: 'lead-1',
    leadNumber: 'LD-2025-001',
    customerName: 'Sunil Gavaskar (Greenway Textiles)',
    scheduledDate: '2025-02-16T10:00:00Z',
    surveyorName: 'Er. Sandeep Joshi',
    roofLengthFt: 200,
    roofWidthFt: 125,
    roofAreaSqFt: 25000,
    roofTiltAngle: 18,
    azimuthDirection: 'True South (180°)',
    shadingFactorPct: 98,
    structureType: 'Trapezoidal Metal Sheet Clamp Structure',
    meterType: 'Three Phase Net Metering Ready',
    discomConnection: 'HT 11kV Substation',
    cableDistanceMeters: 75,
    notes: 'Excellent roof condition. Zero shadow obstructions. Easy crane access for panel lifting.',
    status: 'SCHEDULED',
  },
  {
    id: 'surv-2',
    surveyNumber: 'SURV-2025-002',
    leadId: 'lead-3',
    leadNumber: 'LD-2025-003',
    customerName: 'Kavita Deshmukh',
    scheduledDate: '2025-02-01T11:00:00Z',
    completedDate: '2025-02-01T14:30:00Z',
    surveyorName: 'Er. Sandeep Joshi',
    roofLengthFt: 30,
    roofWidthFt: 30,
    roofAreaSqFt: 900,
    roofTiltAngle: 20,
    azimuthDirection: 'South-West (210°)',
    shadingFactorPct: 92,
    structureType: 'Elevated High-Rise HDG Frame',
    meterType: 'Single Phase Bidirectional Meter',
    discomConnection: 'LT Residential 230V',
    cableDistanceMeters: 25,
    notes: 'Minor tree shade on East corner after 4 PM. Recommended 8 kW system.',
    status: 'COMPLETED',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'quot-1',
    quotationNumber: 'QT-2025-089',
    leadId: 'lead-3',
    customerId: 'cust-1',
    customerName: 'Kavita Deshmukh',
    customerPhone: '+91 98901 23456',
    systemCapacityKw: 8,
    subtotalAmount: 432000,
    subsidyAmount: 78000,
    taxAmount: 21600,
    totalAmount: 375600,
    paybackPeriodYears: 3.2,
    annualSavingsEst: 116000,
    status: 'APPROVED',
    validUntil: '2025-03-01T23:59:59Z',
    items: [
      {
        id: 'qitem-1',
        productId: 'prod-1',
        productName: 'Helios Apex 540W N-Type TOPCon Mono Panel',
        quantity: 15,
        unitPrice: 14500,
        totalPrice: 217500,
      },
      {
        id: 'qitem-2',
        productId: 'prod-3',
        productName: 'Aether Grid-Tie 10kW Three-Phase Inverter',
        quantity: 1,
        unitPrice: 62000,
        totalPrice: 62000,
      },
      {
        id: 'qitem-3',
        productId: 'prod-6',
        productName: 'Galvanized Mounting Structure 8kW',
        quantity: 8,
        unitPrice: 4200,
        totalPrice: 33600,
      },
      {
        id: 'qitem-4',
        productId: 'prod-7',
        productName: 'Complete BOS Wiring & Earthing Kit',
        quantity: 1,
        unitPrice: 38000,
        totalPrice: 38000,
      },
    ],
    createdAt: '2025-02-02T10:00:00Z',
  },
  {
    id: 'quot-2',
    quotationNumber: 'QT-2025-090',
    leadId: 'lead-2',
    customerName: 'Dr. Ramesh Chandra (City Lifeline Hospital)',
    customerPhone: '+91 94140 88990',
    systemCapacityKw: 100,
    subtotalAmount: 4800000,
    subsidyAmount: 720000,
    taxAmount: 240000,
    totalAmount: 4320000,
    paybackPeriodYears: 3.8,
    annualSavingsEst: 1140000,
    status: 'SENT',
    validUntil: '2025-03-15T23:59:59Z',
    items: [
      {
        id: 'qitem-5',
        productId: 'prod-2',
        productName: 'Helios Bifacial Dual Glass 580W Solar Panel',
        quantity: 172,
        unitPrice: 16800,
        totalPrice: 2889600,
      },
      {
        id: 'qitem-6',
        productId: 'prod-4',
        productName: 'Aether Commercial 50kW String Inverter',
        quantity: 2,
        unitPrice: 215000,
        totalPrice: 430000,
      },
    ],
    createdAt: '2025-02-12T15:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'ORD-2025-045',
    quotationId: 'quot-1',
    customerId: 'cust-1',
    customerName: 'Kavita Deshmukh',
    systemCapacityKw: 8,
    totalAmount: 375600,
    paidAmount: 200000,
    status: 'PROCESSING',
    orderDate: '2025-02-06T11:00:00Z',
    expectedDelivery: '2025-02-25T18:00:00Z',
  },
  {
    id: 'ord-2',
    orderNumber: 'ORD-2025-042',
    quotationId: 'quot-0',
    customerId: 'cust-2',
    customerName: 'Apex Auto Components Ltd',
    systemCapacityKw: 350,
    totalAmount: 14700000,
    paidAmount: 14700000,
    status: 'DELIVERED',
    orderDate: '2025-01-16T10:00:00Z',
    expectedDelivery: '2025-02-10T18:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    projectNumber: 'PRJ-2025-018',
    orderId: 'ord-1',
    customerId: 'cust-1',
    customerName: 'Kavita Deshmukh',
    projectManagerId: 'user-5',
    projectManagerName: 'Priya Iyer',
    systemSizeKw: 8,
    siteAddress: '74 Sunrise Villa, Koregaon Park, Pune',
    city: 'Pune',
    status: 'STRUCTURE_MOUNTING',
    progressPct: 60,
    startDate: '2025-02-07T09:00:00Z',
    targetDate: '2025-02-28T18:00:00Z',
    milestones: [
      { id: 'm-1', name: 'Engineering & SLD Design Approval', sequence: 1, status: 'COMPLETED', completedAt: '2025-02-08T17:00:00Z' },
      { id: 'm-2', name: 'MSEDCL Net Metering Application', sequence: 2, status: 'COMPLETED', completedAt: '2025-02-10T12:00:00Z' },
      { id: 'm-3', name: 'Solar Panels & Inverter Site Delivery', sequence: 3, status: 'COMPLETED', completedAt: '2025-02-12T16:00:00Z' },
      { id: 'm-4', name: 'HDG Mounting Structure Assembly', sequence: 4, status: 'IN_PROGRESS', dueDate: '2025-02-18T18:00:00Z' },
      { id: 'm-5', name: 'DC/AC Cabling & Inverter Interconnection', sequence: 5, status: 'PENDING', dueDate: '2025-02-22T18:00:00Z' },
      { id: 'm-6', name: 'DISCOM Net Meter Testing & Commissioning', sequence: 6, status: 'PENDING', dueDate: '2025-02-28T18:00:00Z' },
    ],
  },
  {
    id: 'proj-2',
    projectNumber: 'PRJ-2025-015',
    orderId: 'ord-2',
    customerId: 'cust-2',
    customerName: 'Apex Auto Components Ltd',
    projectManagerId: 'user-5',
    projectManagerName: 'Priya Iyer',
    systemSizeKw: 350,
    siteAddress: 'Plot A-12, MIDC Chakan, Pune',
    city: 'Pune',
    status: 'COMMISSIONED',
    progressPct: 100,
    startDate: '2025-01-18T09:00:00Z',
    completionDate: '2025-02-10T17:00:00Z',
    milestones: [
      { id: 'm-7', name: 'CEIG Inspector Approval', sequence: 1, status: 'COMPLETED', completedAt: '2025-01-25T17:00:00Z' },
      { id: 'm-8', name: '500kVA Solar Plant Grid Synchronization', sequence: 2, status: 'COMPLETED', completedAt: '2025-02-10T15:00:00Z' },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2025-101',
    customerId: 'cust-1',
    customerName: 'Kavita Deshmukh',
    orderId: 'ord-1',
    projectId: 'proj-1',
    subtotal: 318305,
    taxAmount: 57295,
    totalAmount: 375600,
    paidAmount: 200000,
    balanceAmount: 175600,
    status: 'PARTIALLY_PAID',
    issueDate: '2025-02-06T10:00:00Z',
    dueDate: '2025-02-28T23:59:59Z',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2025-098',
    customerId: 'cust-2',
    customerName: 'Apex Auto Components Ltd',
    orderId: 'ord-2',
    projectId: 'proj-2',
    subtotal: 12457627,
    taxAmount: 2242373,
    totalAmount: 14700000,
    paidAmount: 14700000,
    balanceAmount: 0,
    status: 'PAID',
    issueDate: '2025-01-16T12:00:00Z',
    dueDate: '2025-02-15T23:59:59Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    receiptNumber: 'RCP-2025-078',
    invoiceId: 'inv-1',
    invoiceNumber: 'INV-2025-101',
    customerName: 'Kavita Deshmukh',
    amount: 200000,
    paymentDate: '2025-02-06T14:30:00Z',
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'NEFT-HDFC000123987',
    notes: 'Advance 50% payment received upon order confirmation.',
  },
  {
    id: 'pay-2',
    receiptNumber: 'RCP-2025-060',
    invoiceId: 'inv-2',
    invoiceNumber: 'INV-2025-098',
    customerName: 'Apex Auto Components Ltd',
    amount: 14700000,
    paymentDate: '2025-01-20T11:00:00Z',
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'RTGS-SBIN000882211',
    notes: 'Full turnkey project payment cleared.',
  },
];

export const INITIAL_FOLLOWUPS: FollowUp[] = [
  {
    id: 'fol-1',
    leadId: 'lead-1',
    leadName: 'Sunil Gavaskar (Greenway Textiles)',
    userId: 'user-4',
    userName: 'Siddharth Patel',
    title: 'Site Survey Equipment Preparation & Safety Briefing',
    notes: 'Coordinate with factory manager Mr. Varma for roof access ladder setup.',
    dueDate: '2025-02-16T09:00:00Z',
    isCompleted: false,
    priority: 'URGENT',
  },
  {
    id: 'fol-2',
    leadId: 'lead-2',
    leadName: 'Dr. Ramesh Chandra (City Lifeline Hospital)',
    userId: 'user-4',
    userName: 'Siddharth Patel',
    title: 'Follow up on 100 kW Quotation Approval',
    notes: 'Hospital board meeting scheduled for Tuesday to review green energy ROI.',
    dueDate: '2025-02-17T15:00:00Z',
    isCompleted: false,
    priority: 'HIGH',
  },
  {
    id: 'fol-3',
    leadId: 'lead-4',
    leadName: 'Harpreet Singh (Singh Logistics)',
    userId: 'user-3',
    userName: 'Ananya Verma',
    title: 'Final Price Negotiation Call',
    notes: 'Discuss 2% discount on bulk 180 kW panel procurement.',
    dueDate: '2025-02-15T16:00:00Z',
    isCompleted: true,
    priority: 'MEDIUM',
  },
];

export const INITIAL_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-1',
    productId: 'prod-1',
    productName: 'nitish solar Apex 540W N-Type TOPCon Panel',
    sku: 'PAN-TOP-540',
    type: 'STOCK_IN',
    quantity: 500,
    referenceNo: 'PO-2025-101',
    warehouseLocation: 'Pune Main Logistics Hub',
    userName: 'Siddharth Patel',
    timestamp: '2025-02-01T10:00:00Z',
    notes: 'Bulk stock arrival from solar cell assembly line.',
  },
  {
    id: 'tx-2',
    productId: 'prod-1',
    productName: 'nitish solar Apex 540W N-Type TOPCon Panel',
    sku: 'PAN-TOP-540',
    type: 'ALLOCATION',
    quantity: 180,
    referenceNo: 'PRJ-2025-001',
    warehouseLocation: 'Pune Main Logistics Hub',
    userName: 'Priya Iyer',
    timestamp: '2025-02-12T14:30:00Z',
    notes: 'Allocated 180 panels for 100 kW Industrial Project.',
  },
];

export const INITIAL_ALLOCATIONS: ProjectHardwareAllocation[] = [
  {
    id: 'alloc-1',
    projectId: 'proj-1',
    projectNumber: 'PRJ-2025-001',
    customerName: 'Kavita Deshmukh',
    productId: 'prod-1',
    productName: 'nitish solar Apex 540W N-Type TOPCon Panel',
    sku: 'PAN-TOP-540',
    requiredQty: 180,
    allocatedQty: 180,
    deliveredQty: 180,
    installedQty: 120,
  },
  {
    id: 'alloc-2',
    projectId: 'proj-1',
    projectNumber: 'PRJ-2025-001',
    customerName: 'Kavita Deshmukh',
    productId: 'prod-3',
    productName: 'Commercial String Inverter 50 kW 3-Phase',
    sku: 'INV-STR-50K',
    requiredQty: 2,
    allocatedQty: 2,
    deliveredQty: 2,
    installedQty: 2,
  },
];

export const INITIAL_INSTALLATIONS: InstallationJob[] = [
  {
    id: 'inst-1',
    installationNumber: 'INST-2025-001',
    projectId: 'proj-1',
    projectNumber: 'PRJ-2025-001',
    customerName: 'Kavita Deshmukh',
    siteAddress: 'Plot 12, MIDC Industrial Area, Chakan, Pune',
    systemSizeKw: 100,
    projectManagerName: 'Priya Iyer',
    installerLeadName: 'Vikram Singh',
    progressPct: 65,
    status: 'IN_PROGRESS',
    startDate: '2025-02-10T09:00:00Z',
    expectedCompletion: '2025-03-25T18:00:00Z',
    stages: [
      { id: 'stg-1', name: 'Material Delivery', stageType: 'MATERIAL_DELIVERY', sequence: 1, status: 'COMPLETED', assignedToName: 'Siddharth Patel', completedDate: '2025-02-12' },
      { id: 'stg-2', name: 'Mounting Structure', stageType: 'MOUNTING', sequence: 2, status: 'COMPLETED', assignedToName: 'Vikram Singh', completedDate: '2025-02-18' },
      { id: 'stg-3', name: 'Panel Installation', stageType: 'PANEL_INSTALLATION', sequence: 3, status: 'IN_PROGRESS', assignedToName: 'Vikram Singh', dueDate: '2025-02-28' },
      { id: 'stg-4', name: 'Inverter Installation', stageType: 'INVERTER_INSTALLATION', sequence: 4, status: 'COMPLETED', assignedToName: 'Anil Mehta', completedDate: '2025-02-22' },
      { id: 'stg-5', name: 'DC Wiring', stageType: 'DC_WIRING', sequence: 5, status: 'IN_PROGRESS', assignedToName: 'Anil Mehta', dueDate: '2025-03-05' },
      { id: 'stg-6', name: 'AC Wiring', stageType: 'AC_WIRING', sequence: 6, status: 'PENDING', assignedToName: 'Anil Mehta', dueDate: '2025-03-10' },
      { id: 'stg-7', name: 'Earthing & Protection', stageType: 'EARTHING', sequence: 7, status: 'PENDING', assignedToName: 'Anil Mehta', dueDate: '2025-03-15' },
      { id: 'stg-8', name: 'Testing & Inspection', stageType: 'TESTING', sequence: 8, status: 'PENDING', assignedToName: 'Priya Iyer', dueDate: '2025-03-20' },
      { id: 'stg-9', name: 'Commissioning & Net Metering', stageType: 'COMMISSIONING', sequence: 9, status: 'PENDING', assignedToName: 'Priya Iyer', dueDate: '2025-03-25' },
    ],
  },
];

export const INITIAL_AUDITLOGS: AuditLog[] = [
  {
    id: 'log-1',
    userName: 'Siddharth Patel',
    userRole: 'SALES_EXECUTIVE',
    action: 'LEAD_CREATED',
    module: 'Leads',
    details: 'Created lead LD-2025-001 (Greenway Textiles 250 kW)',
    timestamp: '2025-02-10T10:30:00Z',
  },
  {
    id: 'log-2',
    userName: 'Ananya Verma',
    userRole: 'SALES_MANAGER',
    action: 'QUOTATION_APPROVED',
    module: 'Quotations',
    details: 'Approved quotation QT-2025-089 for Kavita Deshmukh',
    timestamp: '2025-02-05T15:20:00Z',
  },
  {
    id: 'log-3',
    userName: 'Amitabh Joshi',
    userRole: 'FINANCE',
    action: 'PAYMENT_RECORDED',
    module: 'Invoices',
    details: 'Recorded payment RCP-2025-078 of ₹200,000 for INV-2025-101',
    timestamp: '2025-02-06T14:30:00Z',
  },
];
